### ISSUE TITLE
I am not able to set up the program

### ISSUE THREAD

**Issue by mihail-pop** [ScienceDiscoverer/steamscrd#6]
I already had visual studio 2022 (just finished college where I used it)
After I ran msvs_build and the stuff is set up, nothing happens? if I try to run steamscrd from CMD it's not recognized.

**Comment by ScienceDiscoverer** [comment]
Did you make all these things? I suspect your Visual Studio may be installed in a different folder then the one written in the bat file. Try to find the folder and replace the path to the Visual Studio!

> How to build
> 
> Just double-click the msvc_build.cmd file. Yep. As easy as this. Well, that is, if you have your Visual Studio installed, of course. And if your VS vcvars64.bat file is located at this path:
> 
> set "bat_dir=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
> 
> If not, first of all, make sure the [Visual Studio](https://visualstudio.microsoft.com/downloads/) is installed. In the setup wizard you will see a huge list of useless features and bloat. Only the C++ build tools are actually needed. Switch to Individual components and try to find this in the humongous list:
> 
> MSVC vXXX - VS 202X C++ x64/x86 build tools (Latest)
> 
> After this you will have to merely locate the vcvars64.bat file and copy-paste the path to it into msvc_build.cmd. Then just launch it and wait until it does all the job for you. Yes, you don't even need to install or open the Visual Studio IDE itself. Ever. I recommend you to try out my [Notepad++ C++ IDE](https://github.com/ScienceDiscoverer/npp_msvc_ide), if you like the idea of ditching the bloated, laggy and overengineered VS!

**Comment by mihail-pop** [comment]
I should have mentioned that, yes, I read this and checked already to make sure the path to vcvars64.bat is "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat".

I checked to make sure I have the C++ tools, latest (even tough I knew I wrote c++ projects).
I even updated visual studio 2022 (since I haven't used it since march).

But again, after I double click, there should be a pop up saying it went ok? Because it doesn't.
I tried to open the interface by typing "steamscrd" in Command Promt both in C:\Users\MyUser and in the steamscrd-main directory. 

You know what, I'll do it again, record it and then upload it on youtube and put the link here as a reply.

**Comment by mihail-pop** [comment]
Here it is: https://www.youtube.com/watch?v=7MJqa9ICHRM

**Comment by ScienceDiscoverer** [comment]
:(
 Hmmm, basically, from what I could see in the video... The build process for the libcurl library went as expected and everything seemed to be fine... But then... When my own libs start to get compiled (txt.cpp) the batch file suddenly stops working and exits? So, of course there is no executable present anywhere.

Honestly, I have no idea of why this could happen, for now. I can't replicate this on my machine as all of my libs are compiled without a problems.

**Comment by mihail-pop** [comment]
After I saw your reply I said to give it a shot and try setting it up on a different machine.
Before I used my new laptop that runs windows 11. Just now I used my PC that runs windows 10. Still didn't work.

So really weird it didn't work for me on two different machines but other people manged to use it before. Maybe some stuff updated in the last few months and doesn't work anymore?

The last thing that stand out for me was this 

"The system can't find the path specified." 
![2024-10-10 17_13_46-Desktop 2024 10 10 - 17 10 04 01 mp4 - VLC media player](https://github.com/user-attachments/assets/838b4b92-a728-4db0-b310-d0bf6220ba7e)

It always appears there. Is that how it should be?

**Comment by ScienceDiscoverer** [comment]
I think it always appears, yes... What you can try to do is comment or remove the `@echo off` in the top of batch file.
Then, launch it, but not by double clicking. Rather, open CMD in the folder and type in the name of batch file. Then copy and send the entire log via pastepin or something like that. This way we might be able to see what's actually wrong with it.

**Comment by mihail-pop** [comment]
I removed the @echo off, but the first CMD window still closes when it's done? and launches "sd_msvc_build" CMD window that says "& was unexpected at this time." . I couldn't figure a way to keep it open so I can copy the text.

**Comment by ScienceDiscoverer** [comment]
OK, screw it, lets try to do it the hard way... Can you put a lot of `pause` statements at the lines of CMD file? Then you can just launch it normally and monitor on which line it closes and what does it print out. I hope this won't be too much trouble for you. Debugging batch files are a pain in the rear!

**Comment by mihail-pop** [comment]
hey one important thing I did in college was to learn how to use chatgpt for menial jobs like this :D 

Here is the pastebin with all of it https://pastebin.com/1k2uRkm4

Close to the end, I note in ( ) where the new CMD window starts.

**Comment by ScienceDiscoverer** [comment]
```
Press any key to continue . . .
Press any key to continue . . .
& was unexpected at this time.
D:\steamscrd-main>
```
This is a good start... But I still can't get where this & is located... Can you list here the lines of CMD file where your last working `pause` is and everything else after that?

**Comment by mihail-pop** [comment]
I modified with chatgpt to rename all the pauses "pause 1, pause 2..." and print them with echo. So now you can tell where everything is. 

This is the pastebin with the new output and my modified msvc_build.cmd so that you can see everything.

https://pastebin.com/JPwHaWJ7


Also I can insert more pauses if it's still not clear at
```
 Pause 18
Press any key to continue . . .
Pause 19
Press any key to continue . . .
& was unexpected at this time.
D:\steamscrd-main>
``` 
Just tell me where you need them in the code.

**Comment by ScienceDiscoverer** [comment]
OK, so it seems that we narrowed the bug to the compilation parameters parsing part here:

```
set /p fline=< %name%.cpp
echo Pause 19
pause
 
:parse_loop
for /f "tokens=1,* delims= " %%a in ("%fline%") do (
	if "%%a"=="CONSOLE" set "subsys=CONSOLE"
	if "%%a"=="DSEH" set "seh=/wd4577"
	if "%%a"=="NOPT" set "optim=/Od" & set "linkopt="
	if "%%a"=="NW" set "warns=/w"
	if "%%a"=="SLIB" set "slib=/c"
	if "%%a"=="DLIB" set "dlib=/DLL" & set "dll_imp_exp=/NOIMPLIB /NOEXP" & set "debug=/LD" & set "start_up=/ENTRY:_DllMainCRTStartup"
	if "%%a"=="DLLIE" set "dll_imp_exp="
	if "%%a"=="DBG" set "debug=/MTd /Z7" & set "debug_link=/DEBUG" & set "debug_def=/D DEBUG" & set "no_def_lib=/NODEFAULTLIB:libcmt.lib"
	if "%%a"=="EPMAIN" set "start_up=/ENTRY:mainCRTStartup"
 
	set "fline=%%b"
	echo Pause 20
	pause
	goto :parse_loop
)
 
echo Pause 21
pause
```

Can you insert pause after each line after pause 19 and pause 20/21? Maybe this way we can see that accursed ampersand...

P.S. I usually use regex instead of generative ai for manual tasks.

**Comment by mihail-pop** [comment]
To make sure I ended up adding a pause after each line in the whole code.

```
...
Pause 38
Press any key to continue . . .
Pause 39
Press any key to continue . . .
Pause 40
Press any key to continue . . .
Pause 41
Press any key to continue . . .
& was unexpected at this time.
D:\steamscrd-main>
```

it still ends up stopping here. So it looks like it stops at the for. Chatgpt said you get that error there because fline contains a special character like &. Even suggested a fix that didn't work and gave a different error :D . But I could also do "echo fline: %fline%" like he said to see the contets.  I would have done it now but I need to leave for the next hours. Tell me if you want that aswell.   (and we also learned/used a bit regex, the lab teacher showed us how he uses regex to search stuff faster in his projects)

```
echo Pause 40
pause

set /p fline=< %name%.cpp
echo Pause 41
pause

:parse_loop
for /f "tokens=1,* delims= " %%a in ("%fline%") do (
echo Pause 42
pause
    if "%%a"=="CONSOLE" set "subsys=CONSOLE"
echo Pause 43
pause
    if "%%a"=="DSEH" set "seh=/wd4577"
echo Pause 44
pause
    if "%%a"=="NOPT" set "optim=/Od" & set "linkopt="
echo Pause 45
pause
    if "%%a"=="NW" set "warns=/w"
echo Pause 46
pause
    if "%%a"=="SLIB" set "slib=/c"
echo Pause 47
pause
    if "%%a"=="DLIB" set "dlib=/DLL" & set "dll_imp_exp=/NOIMPLIB /NOEXP" & set "debug=/LD" & set "start_up=/ENTRY:_DllMainCRTStartup"
echo Pause 48
pause
    if "%%a"=="DLLIE" set "dll_imp_exp="
echo Pause 49
pause
    if "%%a"=="DBG" set "debug=/MTd /Z7" & set "debug_link=/DEBUG" & set "debug_def=/D DEBUG" & set "no_def_lib=/NODEFAULTLIB:libcmt.lib"
echo Pause 50
pause
    if "%%a"=="EPMAIN" set "start_up=/ENTRY:mainCRTStartup"
echo Pause 51
pause
    set "fline=%%b"
    echo Pause 52
    pause
    goto :parse_loop
echo Pause 53
pause
)
```

**Comment by ScienceDiscoverer** [comment]
Yes, you can try to print the `fline`. It should contain the first line of a `.cpp` file that is currently being compiled. Also don't forget to print `%name%` along with it to be sure what file is that.

**Comment by mihail-pop** [comment]
This is it:

```
Pause 40
Press any key to continue . . .
File name: lib\wtxt
fline: // SLIB
Pause 41
Press any key to continue . . .
& was unexpected at this time.
D:\steamscrd-main>
```

Also it gives me hope that earlier it passes through this one called "txt" without issues. So there is something with "wtxt" that might be able to be fixed.

```
Press any key to continue . . .
Pause 40
Press any key to continue . . .
File name: lib\txt
fline: // SLIB
Pause 41
Press any key to continue . . .
Pause 42
Press any key to continue . . .
```


saidjsanjfsdnjfjn WE DID IT. I wrote the part before this earlier then I tried to fix it myself (with chatgpt :D)

Since other people might have this issue, I'll be detailed.

This is what chatGPT said: 

> Ah, I see what’s happening now. The issue is likely due to the format or content of %fline% and how for /f processes it. The & was unexpected at this time. error usually points to an issue with special characters (like &, |, >, <, etc.) being processed in a way that the script isn't expecting.
> 
> Since for /f interprets the content of fline, if there are special characters (e.g., the double slashes //), they might cause an issue. In this case, the line // SLIB seems to be the problem because the for loop is trying to interpret //.
> 
> Fix:
> You can escape special characters (such as & or //) before passing them into the for /f loop.
> 
> Here’s how to escape these characters safely:
> 
> Escape Characters: Replace special characters that might break the for /f loop using setlocal enabledelayedexpansion, so you can safely manipulate the line inside the loop.

> Explanation:
> setlocal enabledelayedexpansion: This allows you to safely manipulate variables (like fline) without causing issues due to special characters like //.
> !fline!: This syntax uses delayed expansion to safely handle fline, avoiding the potential issues with characters like // or &.

So I added `setlocal enabledelayedexpansion` at the start of the file. 
And I changed `for /f "tokens=1,* delims= " %%a in ("%fline%") do (` with `for /f "tokens=1,* delims= " %%a in ("!fline!") do (`

Thing is, I was too excited I didn't wait to test the app (maybe it won't work even if it created the exe). So I'll edit this later and confirm it works. :)

Update: Right now it's downloading the screenshots, it's working! Thanks for the help! And thanks for making the app! (I have 3000 screenshots, no way I could have done it by hand)
